### Como usar:
#
# Docker:
# docker login 
# docker build -t dti-registro.unilab.edu.br/unilab/painelplanejamento:debug .
# dcker tag dti-registro.unilab.edu.br/unilab/painelplanejamento:debug dti-registro.unilab.edu.br/unilab/painelplanejamento:latest
# docker push dti-registro.unilab.edu.br/unilab/painelplanejamento:latest
#
# Compose V2 para compose V1 use 'docker-compose' :
# docker compose up -d
# docker compose logs -f
# docker exec -it painelplanejamento-debug /bin/bash
# docker compose down

version: '3.9'

services:
  ###################################
  # Application
  ################################### 
  app-dev-build:
    build:
      context: .
      dockerfile: $PWD/Dockerfile
      args:
        - COMMIT_SHA=2428676974207265762d7061727365202d2d73686f7274204845414429
        - VERSION=1.0.0
    image: dti-registro.unilab.edu.br/unilab/painelplanejamento:debug
    container_name: painelplanejamento-debug
    restart: always
    ports:
      - "8084:80"
      - "37389:22"
    networks:
      - developer
      
volumes:
  postgresql_data:
    driver: local
    
networks:
 developer:
   name: developer
   driver: bridge
